### ISSUE TITLE
Title: Update ShrineApp Example for Latest Flutter Compatibility

### ISSUE THREAD

**Issue by ghost** [alan-ai/alan-sdk-flutter#19]
Hello Alan AI,

I hope this message finds you well. I am writing to bring to your attention that the ShrineApp example, which is an invaluable resource for the Flutter community, seems to be outdated in terms of compatibility with the latest Flutter updates.

The current version of the ShrineApp is built on an older version of Flutter and uses deprecated properties like `subhead` in the `TextTheme` class, which have been removed or renamed in the recent Flutter SDK releases. This makes it impossible to run the app without errors using the latest stable Flutter SDK.

Updating the ShrineApp will not only help developers who are currently relying on this project for learning and reference but also ensure the continuity of the app as a showcase of best practices in Flutter development.

I, and surely many others, would appreciate your consideration of this request. Your efforts in maintaining this project are highly valued by the community, and an update would reaffirm the app's relevance and utility.

Thank you for your time and for your contributions to the Flutter community.

Best regards,
Tommy Chow

**Comment by snyuryev** [comment]
Thank you for your interest in Alan AI.

Unfortunately, Shrine is not Alan AI's application, our team has just implemented a voice AI assistant for it. Since it is not developed or maintained by our company, we are unable to provide support for it.

If you are looking for examples on how to create a voice enabled Flutter app, please refer to our [Tutorials ](https://www.youtube.com/playlist?list=PLR2FILWn40Kg4E69XIT5d8NqAXmtm1a2k)playlist on YouTube. 

Hope it helps, 

Alan Support Team
